from django.urls import path, include
from rest_framework.routers import DefaultRouter
from .views import (
    StudySessionViewSet,
    StudyEventListCreateAPIView,
    StudyImageListCreateAPIView,
    TodayStatsView,
    RangeStatsView,
    HistorySessionListAPIView,
    HistorySessionDetailAPIView,
    SessionTimelineView,
    ActiveSessionView,
)

router = DefaultRouter()
# The router automatically generates URLs for the ViewSet,
# including standard actions (list, create, etc.) and @action-decorated methods (end, config, objects).
router.register(r'study/sessions', StudySessionViewSet, basename='study-session')

urlpatterns = [
    # Manually define path for the active session view
    path('study/sessions/active/', ActiveSessionView.as_view(), name='active-session-detail'),

    # Include all URLs generated by the router for the StudySessionViewSet
    path('', include(router.urls)),

    # Manually define paths for the other GenericAPIView/ListCreateAPIView classes
    path('edge/events/', StudyEventListCreateAPIView.as_view(), name='edge-events-list-create'),
    path('edge/images/', StudyImageListCreateAPIView.as_view(), name='edge-images-list-create'),

    path('stats/today/', TodayStatsView.as_view(), name='stats-today'),
    path('stats/', RangeStatsView.as_view(), name='stats-range'),

    path('history/sessions/', HistorySessionListAPIView.as_view(), name='history-sessions-list'),
    path('history/session/<int:pk>/', HistorySessionDetailAPIView.as_view(), name='history-session-detail'),
    path('history/session/<int:pk>/timeline/', SessionTimelineView.as_view(), name='history-session-timeline'),
]
